<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework><OutputType>Exe</OutputType><PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems><LangVersion>7.3</LangVersion>
    <TeklaBinPath Condition="'$(TeklaBinPath)' == ''">C:/Program Files/Tekla Structures/2025.0/bin</TeklaBinPath>
    <TeklaStructuresInstallationPath>$(TeklaBinPath)</TeklaStructuresInstallationPath>
    <OutputPath>../../.codex-artifacts/Slot09Check/tests/</OutputPath><AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TSAppConfigPatcherTask" Version="2.1.3" />
    <Compile Include="Program.cs" />
    <Compile Include="HardeningTests.cs" />
    <Compile Include="../../TTSK Dim Plates/TTSK Dim Plates/PHU_DimensionCheck.cs" />
    <Compile Include="../../TTSK Dim Plates/TTSK Dim Plates/PHU_Slot09_ReportForm.cs" />
    <Compile Include="../../TTSK Dim Plates/TTSK Dim Plates/PHU_Slot08_NeighborCleanup.cs" />
    <Compile Include="../../TTSK Dim Plates/TTSK Dim Plates/PHU_MainPartResolver.cs" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="Tekla.Structures"><HintPath>$(TeklaBinPath)/Tekla.Structures.dll</HintPath></Reference>
    <Reference Include="Tekla.Structures.Model"><HintPath>$(TeklaBinPath)/Tekla.Structures.Model.dll</HintPath></Reference>
    <Reference Include="Tekla.Structures.Drawing"><HintPath>$(TeklaBinPath)/Tekla.Structures.Drawing.dll</HintPath></Reference>
    <Reference Include="Tekla.Structures.Geometry3d.Compatibility"><HintPath>$(TeklaBinPath)/Tekla.Structures.Geometry3d.Compatibility.dll</HintPath></Reference>
  </ItemGroup>
</Project>
